# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'finalproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finalproject
  pod 'Alamofire', '~> 5.1'
  pod 'PusherSwift', '~> 8.0'
end

pod 'Parse'
